creating a custom mosquitto broker container
pacefactory/deployment-scripts pull request #43
Opened 2024-09-16 20:13 UTC by hankpacefactory

2024-09-16 20:14 UTC, hankpacefactory commented
https://github.com/pacefactory/deployment-scripts/issues/42

2024-09-16 20:20 UTC, jaredmcgrath requested changes
Add this stuff to a new compose profile, e.g. in `compose/docker-compose.mosquitto.yml`.

Also need to think about API gateway support... if that's even possible? Reason being: some clients only allow us to use e.g. port 80, or 443. Is it possible that we could set this up with a reverse proxy, mapped to a URL like `https://<deployment_url>/api/mosquitto`?

2024-09-17 19:25 UTC, jaredmcgrath reviewed
based on what i'm seeing here + in API gateway, this stuff should work.
Did you test locally? any luck?

2024-09-17 19:25 UTC, jaredmcgrath commented on compose/docker-compose.mosquitto.yml
> +  external_network:
No need for this
```suggestion
```

2024-09-17 20:00 UTC, hankpacefactory commented
> based on what i'm seeing here + in API gateway, this stuff should work. Did you test locally? any luck?

we'll do it live

2024-09-17 20:01 UTC, jaredmcgrath approved these changes

2024-09-17 20:07 UTC, merged